### ISSUE TITLE
Reference file 'path/to/file' does not exist

### ISSUE THREAD

**Issue by paulstretenowich** [IHEC/gemBS#1]
Hi @sitag,
I'm trying to use GemBS on the McGill samples and I can't specify a custom reference. I have the error `Reference file 'path/to/file' does not exist` raising at the prepare step.
My file exists at the right path, I checked with `ls` and opening a python shell doing `os.path.exists("path/to/file")` as it's done inside GemBS script. Have you ever faced that issue?

**Comment by sitag** [comment]
@paulstretenowich No. Not sure I can help you much with this. Please make the issue against Simon's repo.
